//! REST endpoint handlers for the MediChain API.
//!
//! Split out of `main.rs` (Phase 10.2). Each submodule does `use super::*;` to
//! inherit the shared imports below; handlers are glob-re-exported so existing
//! `crate::<handler>` paths (route registration) keep resolving unchanged.

use crate::clinical::*;
use crate::ipfs::{EncryptedMetadata, IpfsError, MedicalRecordReference};
use crate::middleware::error_handling::{secure_tokens, validation};
use crate::nfc_simulator::{NFCCard, NationalIdType, QRCodeData};
use crate::repositories::*;
use crate::state::AppState;
use crate::support::*;
use crate::types::*;
use actix_web::{delete, get, post, put, web, HttpRequest, HttpResponse, Responder};
use chrono::Utc;
use serde::{Deserialize, Serialize};
use sha3::{Digest, Sha3_256};
use uuid::Uuid;

mod access_control;
mod access_logs;
mod auth_challenge;
mod auth_jwt;
mod cds_admin;
mod clinical_scoring;
mod demo;
mod device_lifecycle;
mod emergency_access;
mod emergency_capsule_admin;
mod emergency_grants;
mod gcs;
mod general;
mod identity_claim;
mod identity_context;
mod insurance_cards;
mod ipfs_records;
mod lab;
mod lab_panels;
mod mobile_records;
mod national_id;
mod nfc;
mod nursing;
mod organization_keys;
mod patient_admin;
mod patient_documents;
mod patient_self_service;
mod pdf_export;
mod rbac;
mod retention_admin;
mod sample;
mod session;
mod sms_preferences;
mod soap;
mod staff_credentials;
mod transaction_auth;
mod triage;
mod vitals;
mod wallet_auth;

pub use access_control::*;
pub use access_logs::*;
pub use auth_challenge::*;
pub use auth_jwt::*;
pub use cds_admin::*;
pub use clinical_scoring::*;
pub use demo::*;
pub use device_lifecycle::*;
pub use emergency_access::*;
pub use emergency_capsule_admin::*;
pub use emergency_grants::*;
pub use gcs::*;
pub use general::*;
pub use identity_claim::*;
pub use identity_context::*;
pub use insurance_cards::*;
pub use ipfs_records::*;
pub use lab::*;
pub use lab_panels::*;
pub use mobile_records::*;
pub use national_id::*;
pub use nfc::*;
pub use nursing::*;
pub use organization_keys::*;
pub use patient_admin::*;
pub use patient_documents::*;
pub use patient_self_service::*;
pub use pdf_export::*;
pub use rbac::*;
pub use retention_admin::*;
pub use sample::*;
pub use session::*;
pub use sms_preferences::*;
pub use soap::*;
pub use staff_credentials::*;
pub use transaction_auth::*;
pub use triage::*;
pub use vitals::*;
pub use wallet_auth::*;
