//! PostgreSQL repositories for Phase-7 generic JSON-record feature domains.
//!
//! Every domain shares the `JsonRecordRepository` trait over a uniform
//! `(id, owner_id, data JSONB, created_at, updated_at)` table. One concrete type
//! per domain is generated by `pg_json_repo!` with a **compile-time table
//! literal** — there is no runtime SQL string concatenation, and all values are
//! bound parameters.

use async_trait::async_trait;
use sqlx::PgPool;

use crate::repositories::traits::{JsonRecordEntity, JsonRecordRepository, RepositoryResult};

macro_rules! pg_json_repo {
    ($name:ident, $table:literal) => {
        /// PostgreSQL-backed JSON-record repository (one Phase-7 domain table).
        #[allow(dead_code)]
        #[derive(Debug, Clone)]
        pub struct $name {
            pool: PgPool,
        }

        #[allow(dead_code)]
        impl $name {
            pub fn new(pool: PgPool) -> Self {
                Self { pool }
            }
        }

        #[async_trait]
        impl JsonRecordRepository for $name {
            async fn create(&self, record: JsonRecordEntity) -> RepositoryResult<JsonRecordEntity> {
                let result = sqlx::query_as::<_, JsonRecordEntity>(concat!(
                    "INSERT INTO ",
                    $table,
                    " (id, owner_id, data, created_at, updated_at) \
                     VALUES ($1, $2, $3, $4, $5) \
                     ON CONFLICT (id) DO UPDATE SET \
                        owner_id = EXCLUDED.owner_id, \
                        data = EXCLUDED.data, \
                        updated_at = EXCLUDED.updated_at \
                     RETURNING *"
                ))
                .bind(&record.id)
                .bind(&record.owner_id)
                .bind(&record.data)
                .bind(record.created_at)
                .bind(record.updated_at)
                .fetch_one(&self.pool)
                .await?;
                Ok(result)
            }

            async fn get_by_id(&self, id: &str) -> RepositoryResult<Option<JsonRecordEntity>> {
                let result = sqlx::query_as::<_, JsonRecordEntity>(concat!(
                    "SELECT * FROM ",
                    $table,
                    " WHERE id = $1"
                ))
                .bind(id)
                .fetch_optional(&self.pool)
                .await?;
                Ok(result)
            }

            async fn get_by_owner(
                &self,
                owner_id: &str,
            ) -> RepositoryResult<Vec<JsonRecordEntity>> {
                let result = sqlx::query_as::<_, JsonRecordEntity>(concat!(
                    "SELECT * FROM ",
                    $table,
                    " WHERE owner_id = $1 ORDER BY created_at DESC LIMIT 1000"
                ))
                .bind(owner_id)
                .fetch_all(&self.pool)
                .await?;
                Ok(result)
            }

            async fn list_all(&self) -> RepositoryResult<Vec<JsonRecordEntity>> {
                let result = sqlx::query_as::<_, JsonRecordEntity>(concat!(
                    "SELECT * FROM ",
                    $table,
                    " ORDER BY created_at DESC LIMIT 1000"
                ))
                .fetch_all(&self.pool)
                .await?;
                Ok(result)
            }

            async fn delete(&self, id: &str) -> RepositoryResult<()> {
                sqlx::query(concat!("DELETE FROM ", $table, " WHERE id = $1"))
                    .bind(id)
                    .execute(&self.pool)
                    .await?;
                Ok(())
            }

            async fn replace_if_field_eq(
                &self,
                id: &str,
                field: &str,
                expected: &str,
                record: JsonRecordEntity,
            ) -> RepositoryResult<Option<JsonRecordEntity>> {
                // One statement, so the guard and the write cannot be
                // separated by another transaction. `data ->> $4` reads the
                // *stored* value, not the caller's copy of it — which is what
                // makes a concurrent second approval find `Approved` and lose.
                let result = sqlx::query_as::<_, JsonRecordEntity>(concat!(
                    "UPDATE ",
                    $table,
                    " SET owner_id = $2, data = $3, updated_at = NOW() \
                     WHERE id = $1 AND data #>> string_to_array($4, '.') = $5 \
                     RETURNING *"
                ))
                .bind(id)
                .bind(&record.owner_id)
                .bind(&record.data)
                .bind(field)
                .bind(expected)
                .fetch_optional(&self.pool)
                .await?;
                Ok(result)
            }
        }
    };
}

pg_json_repo!(PgLanguagePreferenceRepository, "language_preferences");
pg_json_repo!(PgEligibilityCheckRepository, "eligibility_checks");
pg_json_repo!(PgSatisfactionSurveyRepository, "satisfaction_surveys");
pg_json_repo!(PgSymptomSessionRepository, "symptom_sessions");
pg_json_repo!(PgFamilyGroupRepository, "family_groups");
pg_json_repo!(PgInsuranceClaimRepository, "insurance_claims");
pg_json_repo!(PgInsuranceCardRepository, "insurance_cards");
pg_json_repo!(PgAutopsyRequestRepository, "autopsy_requests");
pg_json_repo!(PgAutopsyReportRepository, "autopsy_reports");
pg_json_repo!(PgDeathCertificateRepository, "death_certificates");
pg_json_repo!(PgSyncQueueItemRepository, "sync_queue_items");

// Round 5: wearables + telehealth legacy shapes (repos existed but entity shapes
// don't match the rich legacy structs, so these persist losslessly as JSON).
pg_json_repo!(PgWearableDeviceRecordRepository, "wearable_device_records");
pg_json_repo!(
    PgWearableReadingRecordRepository,
    "wearable_reading_records"
);
pg_json_repo!(PgWearableAlertRecordRepository, "wearable_alert_records");
pg_json_repo!(PgWearableAlertRuleRepository, "wearable_alert_rules");
pg_json_repo!(
    PgTelehealthSessionRecordRepository,
    "telehealth_session_records"
);

// Round 6: shape-mismatch domains (legacy structs differ from existing typed
// entities). Persisted losslessly as JSON under distinct table names.
pg_json_repo!(PgEPrescriptionV2Repository, "e_prescription_v2_records");
pg_json_repo!(PgDrugInteractionCheckRepository, "drug_interaction_checks");
pg_json_repo!(PgLabTrendResultRepository, "lab_trend_results");
pg_json_repo!(PgLabResultSubmissionRepository, "lab_result_submissions");

// Round 7: SOAP clinical notes (no prior repository existed).
pg_json_repo!(PgSoapNoteRecordRepository, "soap_note_records");

// Phase 4.3: per-facility CDS thresholds + CDS audit trail.
pg_json_repo!(PgCdsThresholdConfigRepository, "cds_threshold_configs");
pg_json_repo!(PgCdsAuditEntryRepository, "cds_audit_entries");

// Phase 33: offline-sync device registry.
pg_json_repo!(PgSyncDeviceRepository, "sync_devices");

// Horizon HZ-023: real stores replacing fabricated literals.
pg_json_repo!(PgMessageRepository, "messages");
pg_json_repo!(PgSymptomEntryRepository, "symptom_entries");
pg_json_repo!(PgBarcodeScanRepository, "barcode_scans");

// Final durability sweep (migration 20260811000002): the last process-memory
// clinical maps. The first three are shape-mismatch domains whose typed tables
// require columns the API types do not carry — see the migration for why.
pg_json_repo!(
    PgBloodTypeScreenRecordRepository,
    "blood_type_screen_records"
);
pg_json_repo!(
    PgTransfusionEventRecordRepository,
    "transfusion_event_records"
);
pg_json_repo!(PgEPrescriptionRecordRepository, "e_prescription_records");
pg_json_repo!(PgDispenseEventRepository, "dispense_events");
pg_json_repo!(
    PgPrescriptionVerificationEventRepository,
    "prescription_verification_events"
);
pg_json_repo!(
    PgDeathCertificateRecordRepository,
    "death_certificate_records"
);
pg_json_repo!(PgFamilyHistoryRecordRepository, "family_history_records");
pg_json_repo!(PgUserSettingRecordRepository, "user_setting_records");
pg_json_repo!(PgUsedEmergencyTokenRepository, "used_emergency_tokens");
